---
title: "BMT variables"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type= "text/css">

. figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

```{r library}
library(tidyverse)
library(gtsummary)
library(survival)
library(survminer)
```

```{r load}
clinical <-
  read_rds("/Users/colinccm/Documents/GitHub/Gillis/CH_transfer_HCT/clinical.rds")
calls_CH <-
  read_rds("/Users/colinccm/Documents/GitHub/Gillis/CH_transfer_HCT/calls_CH.rds")
```

```{r bind data}
bmt_data <- left_join(calls_CH, clinical,
                      by = c("RecipientMRN" = "recipient_mrn"))
```





# Per Patients data
## Variables
```{r}
bmt_data %>% 
  select(age_bmt, donor_age, race, don_race, sex, don_sex,
         rec_cmv_result, don_cmv_res, karnofsky_score,
         disease_status, conditioning_reg, 
         plt20status, anc500status, 
         cause_of_death) %>% 
  tbl_summary()
```

## Univariate
<div class = "row">
<div class = "col-md-6">
```{r}
bmt_data %>%
  select(age_bmt, donor_age, race, don_race, sex, don_sex,
         rec_cmv_result, don_cmv_res, karnofsky_score,
         disease_status, conditioning_reg, 
         plt20status
         # anc500status
         ) %>%
  tbl_uvregression(method = survival::coxph,
                 y = (Surv(time = bmt_data$os_time, 
                           event = bmt_data$os_event)),
                 exponentiate = TRUE) %>% 
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")

# bmt_data %>%
#   select(
#          plt20status) %>%
#   tbl_uvregression(method = survival::coxph,
#                  y = (Surv(time = bmt_data$os_time, 
#                            event = bmt_data$os_event)),
#                  exponentiate = TRUE) %>% 
#   bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
```
</div>

<div class = "col-md-6">
```{r}
bmt_data %>%
  select(age_bmt, donor_age, race, don_race, sex, don_sex,
         rec_cmv_result, don_cmv_res, karnofsky_score,
         disease_status, conditioning_reg, 
         plt20status) %>%
  tbl_uvregression(method = survival::coxph,
                 y = (Surv(time = bmt_data$relapse_time, 
                           event = bmt_data$relapse_event)),
                 exponentiate = TRUE) %>% 
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
```
</div>
</div>

## Survival

<div class = "row">
<div class = "col-md-6">
```{r, fig.height= 8}
ggsurvplot(survfit(Surv(os_time, os_event) ~ 1, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
)

ggsurvplot(survfit(Surv(os_time, os_event) ~ don_race, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ rec_cmv_result, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ don_cmv_res, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ karnofsky_score, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ disease_status, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ plt20status, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))
```
</div>

<div class = "col-md-6">
```{r, fig.height= 8}
ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ 1, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ race, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ don_race, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ disease_status, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ conditioning_reg, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))
```
</div>
</div>

<br>

***

<br>
<br>

# Donors/recipient

## Variables
```{r}
bmt_data %>% 
  select(race_pairs, sex_pairs,
         cmv_pairs) %>% 
  tbl_summary()
```

## Univariate
<div class = "row">
<div class = "col-md-6">
```{r}
bmt_data %>%
  select(race_pairs, sex_pairs,
         cmv_pairs) %>%
  tbl_uvregression(method = survival::coxph,
                 y = (Surv(time = bmt_data$os_time, 
                           event = bmt_data$os_event)),
                 exponentiate = TRUE) %>% 
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
```
</div>

<div class = "col-md-6">
```{r}
bmt_data %>%
  select(race_pairs, sex_pairs,
         cmv_pairs) %>%
  tbl_uvregression(method = survival::coxph,
                 y = (Surv(time = bmt_data$relapse_time, 
                           event = bmt_data$relapse_event)),
                 exponentiate = TRUE) %>% 
  bold_p(t = .05) %>% add_nevent(location = "level") %>% add_n(location = "level")
```
</div>
</div>

## Survival

<div class = "row">
<div class = "col-md-6">
```{r, fig.height= 8}
ggsurvplot(survfit(Surv(os_time, os_event) ~ 1, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ race_pairs, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ sex_pairs, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))

ggsurvplot(survfit(Surv(os_time, os_event) ~ cmv_pairs, 
                   data = bmt_data),
           title = "OS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))
```
</div>

<div class = "col-md-6">
```{r}
ggsurvplot(survfit(Surv(relapse_time, relapse_event) ~ 1, 
                   data = bmt_data),
           title = "RFS from bmt", 
           font.main = c(24, "bold", "black"), 
           font.x = c(20, "bold", "black"), font.y = c(20, "bold", "black"), 
           font.legend = c(14, "bold", "black"), font.tickslab = c(18, "bold", "black"), 
           size = 1.5,
           
           pval=TRUE, 
           # legend.labs=c(""),
           # palette = c("black", "green","blue", "red"), 
           # Add risk table
           risk.table = "abs_pct", risk.table.title = "Risk table (number(%))",
           risk.table.y.text = FALSE, risk.table.fontsize = 3, tables.height = 0.3,
           tables.theme = theme_survminer(base_size = 5,
                                          font.main = c(16, "bold", "black"),
                                          font.x = c(16, "bold", "black"),
                                          font.y = c(16, "bold", "transparent"),
                                          font.tickslab = c(19, "bold", "black")
           ),
           
           legend.title = "", xlab = "Time (in months)" 
) + guides(colour = guide_legend(ncol = 1))
```
</div>
</div>

# CH status

```{r}

```








